## Deliverable 3. Create a Travel Itinerary Map.

In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [16]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
cities = pd.read_csv("../Vacation_Search/WeatherPy_Vacation.csv")
cities.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Butaritari,KI,81.99,moderate rain,3.0707,172.7902,Isles Sunset Lodge
1,4,Sao Filipe,CV,74.79,overcast clouds,14.8961,-24.4956,Hotel Xaguate
2,5,Kapaa,US,84.18,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
3,6,Bengkulu,ID,75.52,moderate rain,-3.8004,102.2655,Grage Hotel Bengkulu
4,8,Ribeira Grande,PT,70.30,broken clouds,38.5167,-28.7000,Quinta da Meia Eira

In [17]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
import gmaps

gmaps.configure(api_key=g_key)

fig = gmaps.figure()

#Adding markers.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in cities.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = cities[["Lat", "Lng"]]

In [18]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 4b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
my_itin = cities[cities["Country"] == "ES"]
my_itin

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
26,51,Los Llanos De Aridane,ES,67.75,clear sky,28.6585,-17.9182,Valle Aridane
116,237,Mataro,ES,88.84,clear sky,41.5421,2.4445,URH Ciutat de Mataró
170,337,Carballo,ES,65.89,broken clouds,43.2130,-8.6910,Pazo do Souto
175,345,Aguimes,ES,68.67,few clouds,27.9054,-15.4461,Hotel Villa de Aguimes
198,396,Ripoll,ES,72.37,clear sky,42.2006,2.1903,Hotel Solana Del Ter
338,654,La Rioja,ES,69.58,scattered clouds,42.2500,-2.5000,Casa Concejos
341,658,Tarifa,ES,82.42,clear sky,36.0139,-5.6070,Hostel Facundo
353,677,Santa Cruz De La Palma,ES,71.74,clear sky,28.6835,-17.7642,H10 Taburiente Playa
355,681,Aviles,ES,73.18,clear sky,43.5547,-5.9248,"Palacio de Avilés, Affiliated by Meliá"

In [25]:
my_itin.reset_index(drop =True, inplace = True)
my_itin

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,51,Los Llanos De Aridane,ES,67.75,clear sky,28.6585,-17.9182,Valle Aridane
1,237,Mataro,ES,88.84,clear sky,41.5421,2.4445,URH Ciutat de Mataró
2,337,Carballo,ES,65.89,broken clouds,43.2130,-8.6910,Pazo do Souto
3,345,Aguimes,ES,68.67,few clouds,27.9054,-15.4461,Hotel Villa de Aguimes
4,396,Ripoll,ES,72.37,clear sky,42.2006,2.1903,Hotel Solana Del Ter
5,654,La Rioja,ES,69.58,scattered clouds,42.2500,-2.5000,Casa Concejos
6,658,Tarifa,ES,82.42,clear sky,36.0139,-5.6070,Hostel Facundo
7,677,Santa Cruz De La Palma,ES,71.74,clear sky,28.6835,-17.7642,H10 Taburiente Playa
8,681,Aviles,ES,73.18,clear sky,43.5547,-5.9248,"Palacio de Avilés, Affiliated by Meliá"

In [37]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = "Mataro"
vacation_end = "Mataro"
city2 = "Aguimes"
city3 = "Ripoll"
city4 = "La Rioja" 

vacation_start = vacation_df.loc[vacation_df["City"] == vacation_start]
vacation_end = vacation_df.loc[vacation_df["City"] == vacation_end]  
vacation_stop2 = vacation_df.loc[vacation_df["City"] == city2]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == city3] 
vacation_stop4 = vacation_df.loc[vacation_df["City"] == city4]

In [38]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop4[["Lat", "Lng"]].to_numpy()[0]

In [39]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop2,vacation_stop3,vacation_stop4],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,237,Mataro,ES,88.84,clear sky,41.5421,2.4445,URH Ciutat de Mataró
1,345,Aguimes,ES,68.67,few clouds,27.9054,-15.4461,Hotel Villa de Aguimes
2,396,Ripoll,ES,72.37,clear sky,42.2006,2.1903,Hotel Solana Del Ter
3,654,La Rioja,ES,69.58,scattered clouds,42.2500,-2.5000,Casa Concejos

In [41]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [42]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))